DeliverySystem/admin/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint,jsonify, session
from flask_login import login_user, current_user, logout_user
from DeliverySystem import bcrypt
from DeliverySystem.models import Admin
from DeliverySystem.admin.forms import (LoginForm,RequestResetForm, ResetPasswordForm, AddItemForm)
from DeliverySystem.admin.utils import (send_reset_email, save_uploaded_file, read_customer_info_from_csv, 
                                        update_csv_order_status, send_order_state_change_email)
from DeliverySystem.admin.patterns import VegetableInventoryManager, Vegetable, StockObserver, Order

admin = Blueprint('admin', __name__)


inventory_manager = VegetableInventoryManager()
stock_observer = StockObserver()
inventory_manager.add_observer(stock_observer)

@admin.route("/admin_login", methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()

    if form.validate_on_submit():
        admin = Admin.get_by_email(form.email.data)
        if admin and bcrypt.check_password_hash(admin.password, form.password.data):
            login_user(admin)
            flash('Login successful!', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('admin.stock'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')

    return render_template('admin_login.html', title='Login', form=form)


@admin.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@admin.route("/reset_password", methods=['GET', 'POST'])
def reset_request():

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RequestResetForm()

    if form.validate_on_submit():
        admin = Admin.get_by_email(form.email.data)
        if admin:
            send_reset_email(admin)
            flash('An email has been sent with instructions to reset your password.', 'info')
            return redirect(url_for('admin.login'))

    return render_template('reset_request.html', title='Reset Password', form=form)


@admin.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    admin = Admin.verify_reset_token(token)
    if admin is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('admin.reset_request'))
    
    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        admin.password = hashed_password
        admin.save(hashed_password)
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('admin.login'))

    return render_template('reset_token.html', title='Reset Password', form=form)


@admin.route('/additem', methods=['GET', 'POST'])
def additem():
    form = AddItemForm()

    if form.validate_on_submit():
        image_filename = save_uploaded_file(form.image.data)

        new_vegetable = Vegetable(
            name=form.name.data,
            description=form.description.data,
            price=form.price.data,
            num_items=form.num_items.data,
            image=image_filename
        )

        inventory_manager.add_item(new_vegetable)

        flash('New Item has been Added!', 'success')
        return redirect(url_for('admin.stock'))

    return render_template('additem.html', title="Add Item", form=form)

@admin.route('/admin/stock')
def stock():
    inventory_manager.load_from_csv()
    
    stock_data = inventory_manager.display_stock()
    print(stock_data)
    return render_template('stock.html', title="Stock", vegetables=stock_data)

@admin.route('/update_quantity', methods=['POST'])
def update_quantity():
    data = request.get_json()
    vegetable_name = data.get('vegetable_name')
    new_quantity = int(data.get('new_quantity'))
    inventory_manager.update_stock(vegetable_name, new_quantity)

    return jsonify({'message': 'Quantity updated successfully'})

@admin.route("/order")
def orders():
    billing_info_path = 'billing_info.csv'  
    order_info= read_customer_info_from_csv(billing_info_path)

    return render_template('orders.html', title="Orders", order_info=order_info)

@admin.route('/update_order_status', methods=['POST'])
def update_order_status():

    order_id = request.form.get('order_id')
    new_state = request.form.get('new_state')

    initial_order_state = 'Ordered'
    order = Order(order_id= order_id, status=initial_order_state)

    order.update_status(new_state)
    csv_path = 'billing_info.csv'
    update_csv_order_status(order.order_id, new_state, csv_path)
    send_order_state_change_email(order_id, new_state)

    return jsonify({'message': f'Status updated to {new_state} for order {order.order_id}'})

DeliverySystem/main/routes.py
import ast
import json
from datetime import datetime
from uuid import uuid4
from flask import render_template, request, Blueprint, redirect, url_for, flash, jsonify,session
from DeliverySystem.main.utils import (read_vegetables_from_csv, save_customer_info_to_csv, calculate_discount,save_order_to_csv,
                                       read_customer_info_from_csv, remove_order_from_csv,get_cart_items, send_order_confirmation_email, 
                                       get_order_info_by_id,send_order_removal_email,reduce_quantity)
from DeliverySystem.main.patterns import ProductBuilder, DiscountDecorator
from DeliverySystem.main.patternsB import (PaytmPaymentStrategy, CreditCardPaymentStrategy, 
                                           GenerateBillCommand, ExecutePaymentCommand, BillingObserver,BillingService,calculate_total_amount )
from DeliverySystem.main.forms import BillingForm, PayTMForm, CreditCardForm

main = Blueprint('main', __name__)

credit_card_strategy = CreditCardPaymentStrategy()
paytm_strategy = PaytmPaymentStrategy()
billing_service = BillingService()
billing_observer = BillingObserver()
billing_service.add_observer(billing_observer)

generate_bill_command = GenerateBillCommand(billing_service)
execute_payment_command_credit_card = ExecutePaymentCommand(credit_card_strategy)
execute_payment_command_paytm = ExecutePaymentCommand(paytm_strategy)

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')

@main.route("/about")
def about():
    return render_template('about.html', title="About")

@main.route("/contact")
def contact():
    return render_template('contact.html', title="Contact")

@main.route("/shop", methods=['GET', 'POST'])
def shop():
    vegetables = read_vegetables_from_csv()
    session.setdefault('cart', {})

    if request.method == 'POST':
        vegetable_name = request.form.get('vegetableName')
        quantity_str = request.form.get('quantity')

        if not vegetable_name or not quantity_str:
            return jsonify({'error': 'Both vegetable name and quantity are required'}), 400

        try:
            quantity = int(quantity_str)
        except ValueError:
            return jsonify({'error': 'Invalid quantity value'}), 400

        if vegetable_name in vegetables:
            product = vegetables[vegetable_name]
            available_quantity = product.stock

            if int(available_quantity) >= int(quantity):
                cart = session['cart']
                if vegetable_name in cart:
                    cart[vegetable_name]['quantity'] += quantity
                else:
                    cart[vegetable_name] = {'quantity': quantity, 'price': product.price}
                session.permanent = True
                product.add_to_cart(quantity)

                return jsonify({'message': 'Product added to cart successfully'})
            else:
                return jsonify({'message': 'Not enough quantity available'})
        else:
            return jsonify({'message': 'Product not found'}), 404

    return render_template('shop.html', title="Shop", vegetables=vegetables)



@main.route("/cart")
def cart():
    cart_data = get_cart_items()
    print("Cart Items:", cart_data)
    return render_template('cart.html', title="Cart", cart=cart_data)

@main.route("/remove_item/<vegetable_name>", methods=['POST'])
def remove_item(vegetable_name):
    cart = session.get('cart', {})
    if vegetable_name in cart:
        del cart[vegetable_name]
        session['cart'] = cart
        return jsonify({'message': 'Item removed successfully'})
    else:
        return jsonify({'message': 'Item not found in the cart'}), 404
    
@main.route("/get_totals", methods=['POST'])
def get_totals():
    total_quantity = 0
    total_price = 0

    discount_percentage = session.get('discount_percentage', 0)

    for vegetable_name, item in session.get('cart', {}).items():
        product = ProductBuilder(vegetable_name).set_price(item['price']).set_stock(100).build()
        discounted_product = DiscountDecorator(product, discount_percentage)

        total_quantity += item['quantity']
        total_price += product.get_total_price(item['quantity'])

    return jsonify({
        'totals': {
            'totalQuantity': total_quantity,
            'totalPrice': total_price,
            'discountApplied': discount_percentage
        }
    })



@main.route("/check_login", methods=['GET'])
def check_login():
    user_email = session.get('email')
    logged_in = user_email is not None

    return jsonify({'logged_in': logged_in})

@main.route('/set_checkout_session', methods=['POST'])
def set_checkout_session():
    discount_percentage = request.form.get('discount_percentage')
    discounted_price = request.form.get('discounted_price')
    session['discount_percentage'] = discount_percentage
    session['discounted_price'] = discounted_price

    return jsonify({'message': 'Checkout session set successfully'})

@main.route("/billing", methods=['GET', 'POST'])
def billing():
    form = BillingForm()

    if form.validate_on_submit():
        customer_info = {
            'first_name': form.first_name.data,
            'last_name': form.last_name.data,
            'address': form.address.data,
            'city': form.city.data,
            'state': form.state.data,
            'postal_code': form.postal_code.data,
            'country': form.country.data,
            'phone_number': form.phone_number.data,
            'email': form.email.data,
            'payment_method': form.payment_method.data
        }

        save_customer_info_to_csv(form)

        cart = session.get('cart', {})

        total_quantity = sum(item['quantity'] for item in cart.values())
        total_price = calculate_total_amount(cart)
        discount_info = calculate_discount(cart)
        discount_percentage = discount_info['discount_percentage']
        discounted_total_price = discount_info['discountedTotalPrice']
        
        order_id = str(uuid4())
        order_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        orders = {
            'order_id': order_id,
            'order_date': order_date,
            'customer_info': customer_info,
            'payment_method': form.payment_method.data,
            'cart': cart,
            'total_quantity': total_quantity,
            'total_price': total_price,
            'discount_percentage':discount_percentage,
            'discounted_total_price': discounted_total_price
        }

        save_order_to_csv(orders)

        flash('Billing information saved successfully!', 'success')

        bill_result = generate_bill_command.execute(customer_info, cart)
        print(bill_result)

        if form.payment_method.data == 'credit_card':
            execute_payment_command_credit_card.execute(customer_info, cart)
            return redirect(url_for('main.credit_card_details'))
        elif form.payment_method.data == 'paytm':
            execute_payment_command_paytm.execute(customer_info, cart)
            return redirect(url_for('main.paytm_details'))
        else:
            flash('Invalid payment method selected', 'danger')
            return redirect(url_for('main.billing'))


    return render_template('billing.html', title='Billing', form=form)

@main.route("/paytm_details", methods=['GET', 'POST'])
def paytm_details():
    form = PayTMForm()
    if form.validate_on_submit():
        session['paytm_details'] = {
            'paytm_id' : form.paytm_id.data,
            'phone_number': form.phone_number.data,
            'pin': form.pin.data
        }
        flash('Payment made successfully!', 'success')
        return redirect(url_for('main.order_confirmation'))

    return render_template('paytm_details.html', title='Paytm Details', form=form)

@main.route('/credit_card_details', methods=['GET', 'POST'])
def credit_card_details():
    form = CreditCardForm()

    if form.validate_on_submit():
        session['credit_card_details'] = {
            'credit_card_number': form.credit_card_number.data,
            'expiry_date': form.expiry_date.data,
            'cvv': form.cvv.data
        }
        flash('Payment made successfully!', 'success')
        return redirect(url_for('main.order_confirmation'))

    return render_template('credit_card_details.html', title='Credit Card Details', form=form)

from operator import itemgetter

@main.route("/order_confirmation")
def order_confirmation():
    
    cart = session.get('cart', {})
    billing_info_path = 'billing_info.csv'  
    order_info_list = read_customer_info_from_csv(billing_info_path)
    sorted_order_info_list = sorted(order_info_list, key=itemgetter('order_date'), reverse=True)
    latest_order_info = sorted_order_info_list[0]
    for order_info in latest_order_info:
        order_id = latest_order_info['order_id']
        email = latest_order_info['email']

    send_order_confirmation_email(email, latest_order_info)
    reduce_quantity(cart)
    session['cart'] = {}
    return render_template('order_confirmation.html', title='Order Confirmation', order_info=latest_order_info, cart=cart)


@main.route('/my_orders')
def my_orders():
    if 'user_id' not in session:
        return redirect(url_for('users.login'))
    billing_info_path = 'billing_info.csv'  
    order_info = read_customer_info_from_csv(billing_info_path)

    return render_template('my_orders.html', title='My Orders',order_info=order_info)

@main.route('/order_details/<order_id>')
def order_details(order_id):
    billing_info_path = 'billing_info.csv'  
    order_info = read_customer_info_from_csv(billing_info_path)
    for order in order_info:
        if order['order_id'] == order_id:
            if 'cart' in order and isinstance(order['cart'], str):
                order['cart'] = ast.literal_eval(order['cart'])
            index = order_info.index(order)

    return render_template('order_details.html', order_info = order_info, index = index)

DeliverySystem/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% if title %}
        <title>FreshFarmFinds - {{ title }}</title>
    {% else %}
        <title>FreshFarmFinds</title>
    {% endif %}
    <style>
      body {
             background: linear-gradient(to bottom, #4CAF50, #2196F3);
           }
    </style>
</head>
<body id="endblock_content">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
</body>
</html>

DeliverySystem/templates/shop.html
{% extends "layout.html" %}
{% block content %}
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stock.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script type="text/javascript" src="{{ url_for('static', filename='shop.js') }}"></script>
    <script> var shopUrl = "{{ url_for('main.shop') }}";</script>
  </head>

  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/"><i class="fas fa-tractor"></i>FreshFarmFinds</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.home') }}"><i class="fas fa-home"></i> Home</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.shop') }}"><i class="fas fa-shopping-cart"></i> Shop</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.about') }}"><i class="fas fa-info-circle"></i> About Us</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.contact') }}"><i class="fas fa-envelope"></i> Contact Us</a></li>
            </ul>
            <!-- Navbar Right Side -->
            <ul class="navbar-nav">
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.my_orders') }}"><i class="fas fa-clipboard-list"></i> My orders</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.cart') }}"><i class="fas fa-shopping-cart"></i> Cart</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="main">
      <div class="section-container">
        <section class="shop-container">
          <div class="row row-container">
            {% for vegetable_name, vegetable_info in vegetables.items() %}
              <div class="card">
                <img src="{{ url_for('static', filename='images/' + vegetable_info['image']) }}" class="card-img-top" alt="{{ vegetable_name }}">
                <div class="card-body">
                  <h4 class="card-title">{{ vegetable_name }}</h4>
                  <p class="card-text">Price: Rs{{ vegetable_info['price'] }} per kg</p>
                  <p class="card-text" id="{{ vegetable_name }}-stock">Available: {{ vegetable_info['stock'] }} kg</p>
                  <!-- Vegetable Count Controls -->
                  <div class="d-flex justify-content-between">
                    <button class="btn btn-outline-primary" onclick="decrementCount('{{ vegetable_name }}')">-</button>
                    <span id="{{ vegetable_name }}-count" class="count">0</span>
                    <button class="btn btn-outline-primary" onclick="incrementCount('{{ vegetable_name }}')">+</button>
                  </div>
                </div>
                <button class="btn btn-primary" onclick="addToCart('{{ vegetable_name }}', '{{ vegetable_info.price }}')">Add to Cart</button>
              </div>
            {% endfor %}
          </div>
        </section>
      </div>
    </div>
    <footer class="text-center text-lg-start text-white" style="background-color:#343a40; width: 100%;">
      <div class="footer-container p-4 pb-0">
          <section class="">
              <div class="row footer-row">
                  <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Fresh Farm Finds</h6>
                      <p>
                          Explore a variety of fruits, vegetables, and other farm finds directly from 
                          local growers. Our commitment to freshness ensures you get the best quality produce.
                      </p>
                  </div>
                  <hr class="w-100 clearfix d-md-none" />
                  <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
                      <p><a class="text-white">Fruits</a></p>
                      <p><a class="text-white">Vegetables</a></p>
                      <p><a class="text-white">Dry Fruits</a></p>
                      <p></p><a class="text-white">dairy Products</a></p>
                  </div>
                  <hr class="w-100 clearfix d-md-none" />
                  <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
                      <p><a class="text-white">Your Account</a></p>
                      <p><a class="text-white">Become an Affiliate</a></p>
                      <p><a class="text-white">Shipping Rates</a></p>
                      <p><a class="text-white">Help</a></p>
                  </div>
                  <hr class="w-100 clearfix d-md-none" />
                  <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
                      <p><i class="fas fa-home mr-3"></i>Kalavakam,OMR,Chennai,TN</p>
                      <p><i class="fas fa-envelope mr-3"></i>FreshFarmFinds@gmail.com</p>
                      <p><i class="fas fa-phone mr-3"></i>+ 91 95978 89023</p>
                      <p><i class="fas fa-print mr-3"></i>+ 0424 234 567</p>
                  </div>
              </div>
          </section>
          <hr class="my-3">
              <div class="row d-flex align-items-center">
                  <div class="col-md-7 col-lg-8 text-center text-md-start">
                      <div class="p-3">
                          © 2023 Copyright:
                          <a class="text-white" href="{{ url_for('main.home') }}">FreshFarmFinds</a>
                      </div>
                  </div>
                  <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-facebook-f"></i></a>
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-twitter"></i></a>
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-google"></i></a>
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-instagram"></i></a>
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-js"></i></a>
                  </div>
              </div>
          </section>
      </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
{% endblock content %}

DeliverySystem/templates/stock.html
{% extends "layout.html" %}
{% block content %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stock.css') }}">
  <script type="text/javascript" src="{{ url_for('static', filename='stock.js') }}"></script>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/"><i class="fas fa-tractor"></i>FreshFarmFinds</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{{ url_for('main.home') }}"><i class="fas fa-home"></i> Home</a>
                  <a class="nav-item nav-link" href="{{ url_for('admin.stock') }}"><i class="fas fa-shopping-cart"></i> Stock</a>
                  <a class="nav-item nav-link" href="{{ url_for('main.about') }}"><i class="fas fa-info-circle"></i> About Us</a>
                  <a class="nav-item nav-link" href="{{ url_for('main.contact') }}"><i class="fas fa-envelope"></i> Contact Us</a>
                </div>
                <!-- Navbar Right Side -->
              <div class="navbar-nav">
                <div class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v"></i> Menu
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{{ url_for('admin.additem') }}">Add Items</a>
                        <a class="dropdown-item" href="{{ url_for('admin.orders') }}">Orders</a>                   </div>
                </div>
                <a class="nav-item nav-link" href="{{ url_for('admin.logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                
            </div>
          </div>
        </nav>
      </header>
      <div class="main">
        <div class="section-container">
          <section class="shop-container">
            <div class="row row-container">
              {% for vegetable_name, vegetable_info in vegetables.items() %}
                  <div class="card">
                    <img src="{{ url_for('static', filename='images/' + vegetable_info['image']) }}" class="card-img-top" alt="{{ vegetable_name }}">
                    <div class="card-body">
                      <h4 class="card-title">{{ vegetable_name }}</h4>
                      <p class="card-text">Price: Rs{{ vegetable_info['price'] }} per kg</p>
                      <p class="card-text" id="{{ vegetable_name }}-stock">Available: {{ vegetable_info['num_items'] }} kg</p>
                      <!-- Vegetable Count Controls -->
                      <div class="d-flex justify-content-between">
                        <button class="btn btn-outline-primary" onclick="decrementCount('{{ vegetable_name }}')">-</button>
                          <span id="{{ vegetable_name }}-count" class="count">0</span>
                        <button class="btn btn-outline-primary" onclick="incrementCount('{{ vegetable_name }}')">+</button>
                      </div>
                    </div>
                    <button class="btn btn-primary" onclick="updateQuantity('{{ vegetable_name }}')">Update Stock</button>
                  </div>
              {% endfor %}
            </div>
        </section>
      </div>
    </div>
    <footer class="text-center text-lg-start text-white" style="background-color:#343a40; width: 100%;">
      <div class="footer-container p-4 pb-0">
          <section class="">
              <div class="row footer-row">
                  <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Fresh Farm Finds</h6>
                      <p>
                          Explore a variety of fruits, vegetables, and other farm finds directly from 
                          local growers. Our commitment to freshness ensures you get the best quality produce.
                      </p>
                  </div>
                  <hr class="w-100 clearfix d-md-none" />
                  <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
                      <p><a class="text-white">Fruits</a></p>
                      <p><a class="text-white">Vegetables</a></p>
                      <p><a class="text-white">Dry Fruits</a></p>
                      <p></p><a class="text-white">dairy Products</a></p>
                  </div>
                  <hr class="w-100 clearfix d-md-none" />
                  <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
                      <p><a class="text-white">Your Account</a></p>
                      <p><a class="text-white">Become an Affiliate</a></p>
                      <p><a class="text-white">Shipping Rates</a></p>
                      <p><a class="text-white">Help</a></p>
                  </div>
                  <hr class="w-100 clearfix d-md-none" />
                  <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
                      <p><i class="fas fa-home mr-3"></i>Kalavakam,OMR,Chennai,TN</p>
                      <p><i class="fas fa-envelope mr-3"></i>FreshFarmFinds@gmail.com</p>
                      <p><i class="fas fa-phone mr-3"></i>+ 91 95978 89023</p>
                      <p><i class="fas fa-print mr-3"></i>+ 0424 234 567</p>
                  </div>
              </div>
          </section>
          <hr class="my-3">
              <div class="row d-flex align-items-center">
                  <div class="col-md-7 col-lg-8 text-center text-md-start">
                      <div class="p-3">
                          © 2023 Copyright:
                          <a class="text-white" href="{{ url_for('main.home') }}">FreshFarmFinds</a>
                      </div>
                  </div>
                  <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-facebook-f"></i></a>
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-twitter"></i></a>
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-google"></i></a>
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-instagram"></i></a>
                      <a class="btn btn-outline-light btn-floating m-1" class="text-white" role="button"><i class="fab fa-js"></i></a>
                  </div>
              </div>
          </section>
      </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
{% endblock content %}